const express = require("express");
const app = express();
const cors = require("cors");
app.use(express.json());
require("dotenv").config();
const PORT = process.env.PORT;
const dbConnection = require("./dbConnection.js");
const userRouter = require("./routes/userRoutes.js");
const sellerRouter = require("./routes/sellerRoutes.js");
const adminRouter = require("./routes/adminRoutes.js");
const authRouter = require("./routes/authRoutes.js");
app.use(cors());
app.use(express.json());
dbConnection;
app.use("/", authRouter);
app.use("/user", userRouter);
app.use("/admin", adminRouter);
app.use("/seller", sellerRouter);
app.listen(PORT, () => console.log(`Server is Running at Port ${PORT}`));
